export const arrayReal= 
[
    "capn jack was washed over the side\nhis crew searched but found not hair nor hide\nno longer the helm\nbut the deep benthic realm\nis where jack will forever reside\n",
    "as a soup bisque is best when served hot\nmade with lobster it hits the right spot\ni think it tastes dreamy\nits so rich and creamy\nits the soup youd be served on a yacht\n",
    "simply add to the grasp of a rhesus\nthe antithesis psychokinesis\nand i guarantee\nits a sure phd\ni wont write it though im antithesis\n",
    "abeds where you sleep in the night\nunless you and your wife had a fight\nthen for you its the couch\nnext time dont be a grouch\njust permit her to think she was right\n",
    "a smiling young fellow from spain\nfell asleep while aloft in a plane\nin spite of his smile it\nwas he who was pilot\nhe never went flying again\n",
    "the man who becomes alcoholic\nis not on a permanent frolic\nso understand please\nits a painful disease\npart genetic and part metabolic\n",
    "its in castles that monarchs reside\nthick stone walls make a safe place to hide\nunless youre by fate\nthe eighth henrys mate\nin which case youd be safer outside\n",
    "configuration is called absolute\nwhen a molecules chiral repute\nis described in a name\nso its structural frame\ncan be drawn without any dispute\n",
    "according to my recollection\nthe buoy was meant for direction\nbut the pilot was drunk\nand the ship is now sunk\nfrom the buoy and bow intersection\n",
    "can you cure my addiction please doc\ni drink coffee nonstop round the clock\nsince my need for caffeine\nand for sugars so keen\nill go broke with two starbucks per block\n",
    "used by audubon arsenic was\na preservative needed because\nas insecticide he\ncould keep bird skins bugfree\nits sweet almond smell stays yes it does\n",
    "my fictional wife is not real\nwhich is part of her charm and appeal\nfirst shes here then shes not\nwhen i miss her a lot\ni await her return with great zeal\n",
    "accipitrine hawks have short wings\nand sharp beaks used for shredding small things\nin woodlands they prey\nfierce killers in grey\nused in falconrypassion of kings\n",
    "this alfalfa is what we call hay\na word that is easier to say\nit is food for our cows\nrarely touched by our sows\nwho prefer to eat junk food all day\n",
    "said the alien lifeform named phred\nwho wore glasses in back of his head\ncause back there was his snoot\nan ten eyeballs to boot\nits my eye doctor bills that i dread\n",
    "binaural means having two ears\nhear crickets soft chirp  or loud cheers\nnot the crickets of course\ncheering makes them quite hoarse\nand a rash on the throat soon appears\n",
    "upon sitting at table to eat\nthe host served small drinks red and sweet\nthe guests drank the stuff\nbut quite soon had enough\nantipastic liqueur of the beet\n",
    "horseback riding requires lots of gear\nborn of need proven year after year\nand a good bearing rein\nis a means to explain\nto the horse the direction we steer\n",
    "in the shell game a walnut is cleft\nand the right side resembles the left\nthis bilateral game\nwhere both halves look the same\nis a twosided venue for theft\n",
    "when the flies were all buzzing today\ni distinctly heard one blowfly say\nive been mated and so\nnow ill zoom down below\nand in beasts open wounds ova lay\n",
    "a crystal with dark bluish hue\nreferred to as  azulene blue \nis used in cosmetics\nwith pleasing aesthetics\nby more than just merely a few\n",
    "an alogisms often absurd\nfrom the start to the very last word\nan illogical claim\nso impossibly lame\nthat it should be embalmed and interred\n",
    "an accountant is paid to count money\nso that shareholders know nothing funny\nis draining their hive\nlest their shares take a dive\nwhen their honey begins to get runny\n",
    "an ambush a deadly surprise\nbut take care if you do it be wise\nnever leave a way out\ncause without any doubt\nyou will not get additional tries\n",
    "why do we call autumn the fall\nwhen all other seasons we call\nby one name could it be\nautumn leaves on a tree\nwhich flutter to earth one and all\n",
    "an attorney is paid for his bark\nwhen hes in for the kill hes a shark\nyou wont like the view\nif hes headed for you\npay up then hell find a new mark\n",
    "adult entertainment is honey\nto a guy with an eye for a bunny\nwith a bod to admire\nas she strips her attire\nand her client of all of his money\n",
    "a babe magnet pulls the chicks in\nso ready and willing to sin\nit doesnt seem fair\nthat they enter his lair\nwearing nothing except for a grin\n",
    "an abecedarian bore\ngot vitamin pills from the store\na b c d and e\nhe gobbled with glee\nbut at f he could swallow no more\n",
    "a mark who is ripe for the taking\nis a babe in the woods  no mistaking\nhis gullible smile\nand his absence of guile\nunless hes a con man whos faking\n",
    "if you ever get caught in a bind\nyou can fight with your fists or your mind\nif your tongue is real glib\nyou can simply ad lib\nand leave all of your troubles behind\n",
    "we have held ourselves back and delayed it\noft spoken of love though not made it\nso he breathed in her ear\nand she liked the idea\nbut not the bad breath that conveyed it\n",
    "hes a dashing and bold buccaneer\nwith a swashbuckling golden career\nhe raided the main\nfrom haiti to spain\nand he stashed all the cash in zaire\n",
    "the bretwalda mercian king offa\npoured scorn on the welsh and did scoffa\nif you dont like my dyke\nyou can go take a hike\nand you cornish can just bugger offa\n",
    "the victim lay wreckageensnared\nwhile the doctor despaired as he cared\nthe police held the lights\nas the priest read the rites\nand the bystander stood by and stared\n",
    "its germane to the purpose if it\nsees both function and form neatly fit\nif it strikes the right tone\nyou can leave well alone\none might say its an apposite hit\n",
    "there was once an amasser of wealth\nwho was told this will not bring you health\nhe was told it a lot\nso he had the man shot\nand that pretty much speaks for itself\n",
    "speaking anthropocentrically i\nwould prefer that we not search the sky\nfor quickwitted ets\nwhod subdue us with ease\ntil we  know what they like in their pie\n",
    "theres little that raises false hopes\nlike our antimicrobial soaps\nfor the strains they should kill\njust return stronger still\nand could soon have us all on the ropes\n",
    "on account of bananas his basset ate\nthe vicar could not serve the mass at eight\nsaid the vet i have found\nwhat is ailing your hound\nits the oils he cant take amyl acetate\n",
    "a street preacher out in the cold\nwas apocalyptically bold\nwhen he yelled understand\nthe last day is at hand\npeople thought it was cars that he sold\n",
    "my mouth hangs wide open agape\ni look like a barbary ape\nsome flies could swoop in\nthen crawl out on my chin\ndont catch me on videotape\n",
    "absentminded i am to a fault\ni forget theres a pole when i vault\ni have this tattoo\nlest i lose my name too\nsince forgetful is just my gestalt\n",
    "our tomatoes this year are abounding\ntheyre lush red and ripe  just astounding\nweve run out of uses\nwere making excuses\nfor produce thats all but dumbfounding\n",
    "i can often turn lead into gold\nor water to wine  im that bold\nbut alchemy fails me\nwhen vanity nails me\nand i try to turn young into old\n",
    "some people with no sense of fun\nrate the limerick low with the pun\nand are even annoyed\nat aesthetically void\nbits of doggrel like this one now done\n",
    "ive penned all these limricks already\nthey and i are about to go steady\nim a serious poet\nbut few of you know it\nso im going to bed with my teddy\n",
    "the adirondacks are great for vacation\nup there at that high elevation\nbut the struggle for breath\nsignals imminent death\nof altitude asphyxiation\n",
    "my spine is a tad out of plumb\nan adjustment is needed by gum\nmy usual tactic\nis to seek chiropractic\nbut i howl under pressure of thumb\n",
    "my marriage seems terribly dull\nim bored simply out of my skull\nwhen i want stimulation\nthe result is frustration\nperhaps nows the time to annul\n",
    "i have acres of arable land\nim lucky that none of its sand\nits my vineyard to be\npinot noir just for me \nambrosia is what i have planned\n",
    "just once in the roman arena\ni was sent in to face a hyena\ni distracted the beast\nhis hostility ceased\nwith hyena chow made by purina\n",
    "a contract between two adults\nshould lead to consistent results\nan agreement less formal\ncan also be normal\nbut be careful when dealing with cults\n",
    "ive come to this court to allege\nthat my neighbor in saying the pledge\nof allegiance the clod\nleaves out under god\nwhich leaves me quite over the edge\n",
    "i am meg  im the worlds cutest pup\nmy worldview is happy and up\nmy tail wags like crazy\ni sleep when im lazy\nand if offered a bone i say yup\n",
    "you may think that my life is prosaic\nbut i live in a mansion archaic\nwith art by chagall\nive my own taj mahal\nfilled with archways and floors of mosaic\n",
    "i would hate to be seen as a critic\nbut theres something here harshly mephitic\nits your breath  it sure stinks\nplease have one or two drinks\nof a mouthwash bacteriolytic\n",
    "to say that a persons a basher\nis to say theyre a hitter a smasher\nin short theyre a boor\nbut wait theres still more\ntheyre a banger a bonker a crasher\n",
    "whatever you say she defers\nalthough under her breath come the slurs\nwith words filled with spite \na backbite a slight \nher murmurs are soft saboteurs\n",
    "from the mornings til midafternoons\nin luzon you can feel the monsoons\nif that werent enough\nhere comes nastier stuff\nbaguios which are monstrous typhoons\n",
    "the old hay farmers crib had backed up\nand resembled an overstuffed cup\nwhen he eyeballed the scene\nhe said what does this mean\ntheres a balefulness present ayup\n",
    "with affamishment foods what you need\nyou would fight for a sesame seed\na small crumb or an ort\nyoud take any old sort\nand youd polish it off with great speed\n",
    "for bahaism oneness is prime\nthat of god and of prophets in time\nof all peoples and races\nits primary place is\nto end all our warfare and crime\n",
    "toss out all of those pepcid ac\ni am now achlorhydric ah me\nno more zantac or tums\nin immeasurable sums \nim a hulk of antacid debris\n",
    "when youre mixing a dextrin thats new\nwith some iodine note the stuffs hue\nso its achroo  clear\nwith erythro reds here\nand its amylodextrin if blue\n",
    "she kicks and she bites and she hits\nand to get what she wants she throws fits\nshe smears food on the wall\nand leaves toys in the hall\nin short her behaviors the pits\n",
    "if you sing as you flit in the air\ngrow brown feathers in place of your hair\nand a buick cars name\nand your own are the same\nyoure alaudine thats all i can swear\n",
    "round the base path the hitter can run\nwhen hes tagged all four bases hes done\nif he first runs to third\nits youre out that is heard\nand his trip to the showers begun\n",
    "acyrology makes you a fool\nby your flouting a dictional rule\nwhen supposablys said\nin supposedlys stead\nfolks will say where did you go to school\n",
    "this aphasia means i cant say\nthat my brain has not had a good day\ni can think but not speak\ncan the frontal lobe tweak\nthereby ending my silent dismay\n",
    "agar agars a weird sort of food\nmade of seaweed first boiled and then stewed\nit makes a firm jelly\nthats not at all smelly\nits food for a prude not a dude\n",
    "some say cadburys is better than lindt\nbut that only applies if youre skint\nfor true chocoholics\nbeguiled by their frolics\nmister cadbury wont cost them a mint\n",
    "you might think that a really good prize\nis a buffalo fullgrown in size\nbut a hoof at each corner\nand sharp horns should warn yer\nto hunt it with only your eyes\n",
    "while hurtling at cool breakneck speed\nshe screamed and he kind of agreed\nwhen driving through town\nits best to slow down\nif staying alive is your need\n",
    "if he thinks that his partner hell lose\nhell be quick to forswear drinking booze\nbut faced with the liquor\nhell change his mind quicker\ncos the booze not the boozer will choose\n",
    "though ive always found limericks fun\nthe oedilfs clever editors stun\nme with rewriting rhymes\nat least five or six times\ntill they finally say it can run\n",
    "the odd discord can sometimes be heard\nin the music of william byrd\nthe question it seems\nwas that clash in my dreams\nor was william true to his word\n",
    "acupuncturists use all their skills\ndiagnosing and treating your ills\nthey may look at your tongue\ncheck your spleen and your lung\nand use needles instead of those pills\n",
    "a cathedral choir sings from the quire\nin those stalls that lie east of the spire\nthe tenors and basses\nare making wry faces\nas the trebles soar higher and higher\n",
    "im more generous now than ive been\nthough you claim im psychotically mean\nim not crazy or mazed\nbut the way i was raised\nmakes me cheapskate when times are so lean\n",
    "if its ace then its really first class\nfrom great food to exquisite cut glass\nin tennis an ace\nreally quickens the pace\nand in cards its a fine coup de grce\n",
    "the musical scale the chromatic\nis dramatic but never erratic\neach semitone rises\nwhich brings no surprises\nlike steps from the cellar to attic\n",
    "when attending a whitewater school\nthe canoeists best friends his cagoule\nwhen immersed in the water\nhes glad that he bought a\nfab cag to keep dry though uncool\n",
    "my god but that womans a yeller\nis it pain or perhaps salmonella\nshe sings music that seems\navantgarde mainly screams\nunaccompaniedall a cappella\n",
    "a bold agapanthus once grew\nin hot sun and in true lovely blue\nand in greek agape\ndefines love so you may\ngive those flowers to say i love you\n",
    "a charcutier once was immersed\nin creating a dog fit to burst\nwith the perfect ingredients\nno cheapskate expedients\nfor the best porcine fest not the wurst\n",
    "i was born with my digits reversed\nwith my pinkies not thumbs coming first\nevery teacup gets smashed\nand my cars somewhat trashed\nwith cackhandedness truly im cursed\n",
    "said the kayaker brushing her breast\nits so rounded and plump is my chest\nthat when rolling my boat\ni will easily float\nwith my buoyancy aid im not stressed\n",
    "now the reo whos called in absente\nmay find that hes forfeited plenty\nhes not there to help out\nthough his lawyers about\nhell be serving a fifteentotwenty\n",
    "an acolythist helps out the priest\nwith the trivial duties at least\nare the candles all lit\nthen hes doing his bit\nto assist with the eucharist feast\n",
    "a colorful things basophilia\nit brings out minute sensibilia\napply basic dyes\nwhat a splendid surprise\nyou can really see all of the cilia\n",
    "anadipsias quite a large thirst\nthough it comes on quite slowly at first\ndont be counted a fool\nstay away from that pool\nor youll drink so much water youll burst\n",
    "anaptyxis inserting a vowel\nis a process that causes a howl\nif two consonants make\na cacophony take\na small break or just throw in the towel\n",
    "no matter your language or idiom\nits tough to define a basidium\nwhatevers it for\nthe basidiospore\nrests upon it inside the peridium\n",
    "what an outdated concept bank money\nbanks still using paper how funny\ncheck credit and draft\ni tell you its daft\nits the twentyfirst century honey\n",
    "the acontias lizards no snake\nso i hope you dont make that mistake\nit is legless thats true\nbut between me and you\nits a skink so i think its a fake\n",
    "baronetcy is hardly a slight\nfor a fellow whos more than a knight\ni dont know if hes carin\nthat hes not a full baron\nbut he hasnt acquired that right\n",
    "a barrooms a place you can buy\nscotch whisky malt liquor or rye\nan adventurous sort\ncan indulge in a snort\nof the oddly named drink emerald eye\n",
    "whats the chatham house rule i declare\ninformation youre welcome to share\nbut you hereby disclaim\nany mention of name\nor alliance and so on elsewhere\n",
    "this mousetrap ive built has no flaw\nits better than others im sure\ntheres no oiling or bait\nill just sit here and wait\nwhile the world beats a path to my door\n",
    "with inflationary pressures persistent\non value in clothes im insistent\nmy pants cost no more\nthan they did years before\nand my shirts  well im in creaseresistant\n",
    "bowl a yorker or doosra or swing\nflipper googly a beamer might sting\ncore of cork bound with leather\nsewn neatly together \nthe cricket balls praises we sing\n",
    "barbarianism describes\nthe folk of uncivilized tribes\nthey rape and they pillage\nfrom village to village\nor so go the cultured folks jibes\n",
    "if youre picking a fight with the gods\nyou are fighting against all the odds\nthey will zap you to dust\nwith a lightning bolt thrust\nget ben franklin to lend you some rods\n",
    "the velvety fabric bagheera\nis something youd want to have near ya\nits crushproof renown\nmakes it great for a gown\nthough it stains if you spill your madeira\n",
    "not too sure if a babys in there\na ballottement will tell you whats where\ngive a push from below\nif it floats back you know\nthat the couple will soon have an heir\n",
    "atraumatic procedures are used\nto insure that the patients not bruised\nhe has suffered enough\nso why put him through stuff\nwhen hes already badly abused\n",
    "with asynergys bodily quirk\nyou might feel like a mighty big jerk\nor a spasm or tic\nmight well do the trick\nof permitting your body to work\n",
    "an abetter was aiding a friend\nat the sands giving money to spend\nthe pal gambled away\nall that hardworkedfor pay\nbut the bettors no better the end\n",
    "on st peters basilican heights\nfar above all the noise and the lights\nmichelangelos dome\nshows the glory of rome\nand is one of the tourist delights\n",
    "in the harbor near baltimore port\nstands mchenry that bastioned old fort\nit was here that the brits\nonce directed their hits\nin the starspangled banners front court\n",
    "when han solo takes on boba fett\nin a carbonite prison hes set\nso now pity poor han\nthe anthropolith man\nhes as stiff as the living can get\n",
    "as i ogled the brand new red garter\ni decided to try on some barter\nwill you take for that hosiery\nmy grandmothers rosary\nyoure joking thats such a nonstarter\n",
    "three eggs with the whites whisked to start\nthen yolks chocolate cream set apart\nabove boiling water\nwhen soft then you oughta\nfold in and say prayers for your heart\n",
    "when shopping for presents in china\nthe beautiful silks are not minor\nbut from watches to shoes\nyoull find labels amuse\nyou as fakes all lay claim to designer\n",
    "he eyes me the glint greenish gold\nuntil in my arms i enfold\nthat smooth sorrel fur\nwrapped around a loud purr\nwhich this rasta cat doesnt withhold\n",
    "chromatically sliding you see\nthree notes move from a up to b\nwhen lotti divides\nhis singers he slides\nthe music from key into key\n",
    "the cheetah a feline with class\nlives in africas desert or grass\nshe can muster vast speed\nto assuage hungers need\nsixtyfive without busting her arse\n",
    "beijing is as smoggy as sin\nsome days youll just want to stay in\nif youre out and about\nwear a masktheres no doubt\nthat without it your chances are thin\n",
    "in the music of doctor john blow\nsounds from voices and instruments flow\nhenry purcell once went\nto this right proper gent\nand learned skills from which dido would grow\n",
    "i emerged red and wrinkled at birth\nwith my humour in evident dearth\ncried my mother in verse\ncant you do something nurse\nfor my babe to have mirth on this earth\n",
    "an antelope down on his luck\nsaw a coin shining bright in the muck\nbut the old silver dollar\nwas pointless to swaller\nso the buck stuck for luck passed the buck\n",
    "most darts players tend to be weighty\nmale beerdrinkers cheerful and matey\nthey let the darts fly\nas they hope for the cry\nfrom the umpire one hundred and eighty\n",
    "winston churchill pm in the war\ntold the house i can offer no more\nthan blood toil tears and sweat\nnow that battle is met\nour aim must be victory he swore\n",
    "the light and the dark blues both meet\neach year for the boat race  a treat\nso far cambridges score\nover oxford five more\nnot counting that single dead heat\n",
    "down below on the great cutty sark\nwith my cutty pipe lit in the dark\non a short spoon i tripped\nand my little pipe slipped\nconflagration ensued from the spark\n",
    "my limericks perhaps could be neater\ni dont get the anapst metre\nill write them but know\ntheyve a long way to go\nso well work on the version thats beta\n",
    "beware  this may scald  contents hot\ndid anyone think it would not\nthis simple precaution\nblown out of proportion\nwinds up meaning diddlysquat\n",
    "its my birthday today and im sure\nthat ive never been this old before\nthough its quarter past three\nwake up  listen to me\ncause im four  yes im four  yes im four\n",
    "the surgeon said hey  how about\nintroducing an element of doubt\nwell play guessthedisease\npatient said with a wheeze\nits a tumour you oaf  cut it out\n",
    "when im crossing myself here is one\nsimple way i remember its done\ntouch the spectacles face\nthen the testicles place\nand the wallet and watch  its such fun\n",
    "the waltz and the quickstep and jive\nall dance steps celebrities strive\nto perform to perfection\navoiding ejection\nbruce forsyth  is he still alive\n",
    "cron is the tool that you seek\nto run code at set times of the week\na crontabs a table\nyou write to enable\nthis wonderful tool of the geek\n",
    "a limerick writer from hove\nwhose work was disliked said by jove\nmy verses feel dated \nthats why they are hated\nthat obsolete writer from hove\n",
    "the goon show is not dead one reads\nits alive and its well for the seeds\nof continuing fame\nin spirit not name\nare thriving at radio leeds\n",
    "cuts of beef youll find butchers prepare\nrump and sirloin delicious when rare\nshin and brisket theyre cheap\nbut unlike pigs or sheep\ncows dont merit a chop  thats not fair\n",
    "the ball was defended by cole\nand over the goalline did roll\nthe cross to be borne a\nquick kick from the corner \na header a strike its a goal\n",
    "to windows and mice i say phooey\ni simply cant work with a gui\ni type my command\nat the prompt understand\njust not format  the disk goes kablooey\n",
    "to longdistance love theres no barrier\nmeet a girl on the net and then marry her\nshell have grace shell have poise \nwhats this though  line noise\nthis crappy old modem  no carrier\n",
    "as a troll id enjoy spoiling news\ncrossposting each thread that id choose\nto recpets or altflame\nit isnt the same\nnow the nets dubdubdub and not use\n",
    "lets talk of this now and not later\ndont think im a leftponder hater\nit causes some friction\nthis matter of diction\nbut beetah is neater than baytah\n",
    "oh daddy is that thing a shrew\nit looks like a guinea pig too\nno no my wee lassie\nthat there is a dassie\nwhos closer to jumbo than you\n",
    "in the tunnel i hid with my lover\nwhen she sensed there was something above er\ndont you worry my sweet\nits the sounds of the street\ncause this tunnel is just cutandcover\n",
    "when building a radio set\nwith a crystal you mustnt forget\nfor results that are brisker\ninstall a cats whisker\nit wont pick up digital yet\n",
    "up the workers  were gonna put right all\ninjustice  were marching to fight all\noppression  those laws\nwrit behind those closed doors \nchuck em out with those tosspots in whitehall\n",
    "this dalek this creature of hate\nwill conquer or kill thats our fate\nour people are fleeing\nthis superior being\nand its battle cry exterminate\n",
    "with mist drifting over the bay\nthe moonlight to sunshine gives way\nthe birdsong will rise\nas i open my eyes\nto my favourite time break of day\n",
    "hes brave and courageous and ballsy\nsees chances where others see walls  he\nclimbed kilimanjaro\nthus raising the bar  oh\ndid i mention his cerebral palsy\n",
    "shes cut up for he constantly lies\nand shes sick of his wandering eyes\nnow her note on the door\nreads youre welcome no more\nand ive cut up your suits socks and ties\n",
    "twice a year id be ranting and raving\nwhen i found all the clocks misbehaving\nthen i picked up the knack\nthats spring forward fall back\nthats the rule when we do daylight saving\n",
    "my barking mad neighbour louise\nhas cut down my leylandii trees\nshe maintains its my right\nmy available light\nwas cut down when they swayed in the breeze\n",
    "should the match be a tense fiveset bout\nor a straight set defeat theres no doubt\nwhen it gets to the news\nreporters will choose\nto say that the loser crashed out\n",
    "the chef screams you waiters are hateable\ndont ask if my pasta is plateable\nor what kind of dish\nshould be used for my fish\nim in charge here  this isnt debateable\n",
    "when cooking i love to deepfry\na mars bar a fish or a pie\ni love eating batter\ni  cough  whats the matter\nmy heart gives a clatter  i die\n",
    "when youre travelling northwards from kerry\nand crossing the shannon by ferry\nyoull miss such a pity\nthis county and city\nthe birthplace of togmeister terry\n",
    "the rebel presents her proposal\nlook king this here knife up your nosell\ndraw royal blood true\nshall we see if its blue\nand thus she effects his deposal\n",
    "it made the new trumpeter quail\nwhen the maestro addressed him to rail\nyou stupid freeloader\nda capo al coda\nmeans play from the head to the tail\n",
    "a longdistance trucker called merv\nat the wheel as he rounded a curve\nsaw some diesel was spilt\nas he drove at full tilt\nmerv unnerved had to swerve round the derv\n",
    "when you sing an alternative tune\nof such beauty you feel you could swoon\nsinging notes that are higher\nthan the rest of the choir\nthen a descants the tune that you croon\n",
    "whoever came up with the dream\nthat two biscuits would work as a team\nwith a soft creamy filler\nthat tastes of vanilla\nlets all cheer for the dear custard cream\n",
    "deciduous trees my young ben\nall have leaves in the summer but then\nin the autumn leaves fall\nwinter no leaves at all\ncome the spring theyll be growing again\n",
    "its a breeze if you breezily breeze\nthrough the form  you will do it with ease \nand just sign on the line\nthen whats yours will be mine\nits a doddle  just go ahead please\n",
    "when the broadcast of seeds was well known\nthey were scattered by hand its been shown\nthat they didnt land straight\nand the blowaway rate\nwas too high few were sown much less grown\n",
    "if its shipshape its quite bristol fashion\nand wont make the captain turn ashen\nhe loves things just right\nclean and sparkling bright\nand a mess drives him into a passion\n",
    "does ones braininess stem from ones genes\nits a topical question and means\nif its so we could start\nto make all kids real smart\nand exterminate megadeth teens\n",
    "oh blusterer take my advice\nand do try your best to think twice\nbefore making a sound\nfor threats empty resound\nand throatjumping comes at a price\n",
    "a metal thats active is one\nthat wants to go out and have fun\nwith an element who\nmight be likeminded too\na compound youll find when theyre done\n",
    "apple corer oh how to endure\na life without you in the drawer \nunable to eat\nan apple so sweet\nwithout having to chomp on the core\n",
    "they divided the fields up among them\nand scattered their seeds  well they slung them\nbut their strips although wide\nhad a baulk at each side\nand so onto the weeds they oft flung them\n",
    "for an adatis cotton is grown\nin india then when its sewn\nits transported afar\nto where clothbuyers are\nand where such cultivations unknown\n",
    "if he lives in a sett underground\nand a stripe on his head can be found\nthen we say that his name\nwell the one of less fame\nis a brock they no longer abound\n",
    "he brutishly brushed her away\nsnarling hey i dont care what you say\nyoure too ugly and fat\nand i wont stand for that\ni feel animalistic today\n",
    "whats shared by your tears and the seas\nand by sweat and the brisk ocean breeze\nits their saltiness but\nsince theyre watery lets put\nthe right word here say brininess please\n",
    "you are bloodguilty thoughts haunt your mind\nlive your life live it out guilt will bind\nyou from now till the end\nfor your conscience wont mend\nyou have killed they will seek let them find\n",
    "hes a breaststroker just watch him swim\nthough on land we all know hes quite dim\nhis big feet turn right out\nand his pull packs a clout \nbut dont tell him that frogs swim like him\n",
    "i need breathing space  back off a bit\nif you dont theres a chance youll get hit\nlet me do my own stuff\ncause youve more than enough\nof your own space in mine you dont fit\n",
    "i was once quite bemused by the fact\nthat my dad loved brown sauce which is packed\nwith baked beanspicing flavour\nbut now i too savour\nthe stuff  so the ketchups been sacked\n",
    "baked cheese is just one of lifes pleasures\nwith honey its something one treasures\nif youve baked the right cheese\nthen youll find with great ease\nthat the taste is not something one measures\n",
    "if you rise in a hotair balloon\nand you study the clouds or monsoon\nits aeroscopy  though\ndont go too high you know\nyou will never float up to the moon\n",
    "a guy who sells meat in a shop\nor a killer whose slayings wont stop\nbut whichever you mean\nthe same outcome is seen \na butcher will give you the chop\n",
    "education shall broaden your mind\nget some schooling and soon you will find\nthat your interests grow\nas will things that you know \nwell unless youre the dull normal kind\n",
    "yes im brimming with fervour i feel\nalmost everything has its appeal\nbut you find things quite dull\nlost their lustre your skull\nmust be brimming with boredom no zeal\n",
    "i snooze underground not too deep\ntill the dawn when i wake up and peep\nwith my bright bunny eyes\nfrom my burrow whose size\nmakes it cosy a warm place to sleep\n",
    "for general use brambly means prickly \nthorned undergrowth tangled up thickly\nbut be scientific\nthe words more specific\nof rubus defines it quite slickly\n",
    "age of moon is the time thats gone by\nsince the new moon hung dark in the sky\nso the heavens werent bright\nfor the suns shining light\nlit its other face up there on high\n",
    "a brattice its used in a mine\nkeeps the air flowing through by design\nmade of cloth or of wood\nseldom stays there for good\nfor a makeshift shaft stopgap its fine\n",
    "an acetoorcein stain\nif youve got coloured dyes on the brain\nis what scientists use\nwhen they wish to see views\nof a squashed chromosomal terrain\n",
    "as a brownie i tried to be good\nto behave as a brownie guide should\nand to help every day\nbut too often id say\nwell i would lend a hand if i could\n",
    "whats a ductulus thats a small chute\nthat allows bile and sweat to commute\nif you mean more than one\ntheyre called ductuli son\nanatomical terms are a hoot\n",
    "dissimule defined think of spies\nhow they live in a world filled with lies\nthey befriend and entreat\nwith disguise and deceit\nthats the meaning that this word implies\n",
    "the butterflies squirm in my guts\nits crunch time  no ifs ands or buts\nthe wriggling inside\nleaves me longing to hide \nand this waiting its driving me nuts\n",
    "the colon a beautiful mark\nneatly balanced no squiggles how stark\nits message is hey\nhere it comes what i say\nfollows on youre not left in the dark\n",
    "ng svefg jung v fnl vf pbaprnyrq\nguvf pelcgbtenz npgf nf n fuvryq\nohg fvapr lbh unir oebxra\ngur pbqr nf n gbxra\nguvf yvzrevpx unf abj orra erirnyrq\n",
    "the braiding that graces your hair\nmakes curious folk stop and stare\nsince you chose not your head\nbut your nose hair instead\nas the place for your hairweaving flair\n",
    "all too swiftly her life flickered past\nshe breathed barely at all then her last\none tide of the seasons\nleft nothing the reasons\nfor loss leave us helpless aghast\n",
    "shes a butterfly girl so she skitters\nfrom task to distraction she flitters\nwith bright eyes aglitter\nim tempted to hit er\nand jitters and twitters and titters\n",
    "red heat and the sweat and the smell\nin the ring where the deathdances swell \ncan bloodshed be art\nno not deep in the heart\nof bullfightings passionate hell\n",
    "adventuristic not me i conform\nto convention keep clear of the storm \nthats my motto no shaker\nor mover trendbreaker\nor setter i stick to the norm\n",
    "often buoyance is punctured apace\nby exams that leave barely a trace\nof my lightness and cheer \nbut hold on not this year\nthe oedilf keeps a smile on my face\n",
    "down the shaft of this bell pit weve sunk\nat the coalface we land with a clunk\nsee the coals hollowed out\nand these pillars  dont shout\na cavein means death are you drunk\n",
    "its a fact thats beyond disputation\nthat germanstyle capitalisation\nin english of nouns\nwould produce puzzled frowns\non the foreheads of folk in this nation\n",
    "lord byron was dashing with dough\nand caroline lamb loved him though\nhe had girls in profusion\nshe wrote in seclusion\nhes mad bad and dangerous to know\n",
    "i can look things up sitting in chairs\non the train at the foot of the stairs\ni dont need multimedia\njust a good cyclopdia\ntheres no en by the way when its pears\n",
    "the cars made a marvellous scene\nthe germans sleek silver machine\nitalian blood red\nfrench blue but who led\nthe british with clean racing green\n",
    "an australian doctor named hook\ndid nothing at all by the book\nno matter how poorly\nhis patient hed surely\nsay nah mate  youre just a bit crook\n",
    "im free stupid boy shut that door\nnice to see you dont mention the war\nand its goodnight from him\nmy names  no  no  no  jim\nyou dirty old man say no more\n",
    "when facing a false accusation\nbeware of unwanted vexation\nreview your defence\nto be sure it makes sense\nand be ready for crossexamination\n",
    "my experiments work heinrich blurts\nbut mean nothing i guess he asserts\nyet cycles per second\nwere named for the fecund\nbrainpower of heinrich theyre hertz\n",
    "many motorcar racers have found\nwhen their cars not mechanically sound\na blackflagging marshal\nwhos strictly impartial\ndecrees to the pits you are bound\n",
    "i was once at a show where i heard\nthat the wi would judge curd\nmade of fruit as a jam\ntry my lemon curd maam\nshe demurred on my curd  it came third\n",
    "for an additive function its true\nthat when f acts on p and on q\nand the answers one sums\nthe grand total becomes\nthe function of p plus q too\n",
    "frozen ground and the twigs tipped with frost\nautumn leaves are all gathered and tossed\nthen the season thats here\nthough it wont last all year\nwe call brumal late sunshine is lost\n",
    "dubbed bubblegummers  oh how unfair\nsome teenagers chew im aware\nthere are many whose jaws\nchamp all day without pause \nbut the rest of us arent all that rare\n",
    "im waiting to burke you i lurk\nin the shadows youll die amidst murk\nand no one will know\nthat my hand dealt the blow\nsince ill leave not a trace of my work\n",
    "youre flushed with excitement  youre glowing\nyour prattle shows no signs of slowing\nyoure bubbling so much\nthat youre warm to the touch\nand your fresh foaming zeals overflowing\n",
    "lets call in a bulwark installer\nto make our stone ramparts still taller\nfor the waves are immense\nand without more defence\nour small island will keep getting smaller\n",
    "its swiftness  not that of an arrow\nbut a bullet  stirs life in the marrow\nof bones that maintain\non this sleek sharpnosed train\nthat the fantasytruth gap is narrow\n",
    "the government wanted to shield\nbritains farmers from corn from afield\nbut the acll\ncried free trade let them sell\nso the corn laws at last were repealed\n",
    "these mushrooms although theyre quite small\narent really like buttons at all\nthough theyre rounded and white\ntheyre more tempting to bite\nand if sewn on a coat theyd appal\n",
    "deep in woodland my dog got her fur\nbadly snarled up with seeds silly cur\nthey are sticky and prickly\nnot picked out so quickly\nwhat a job finding burr after burr\n",
    "that figure is incomprehensible\nim afraid that weve failed to be sensible\nthis breakdown explains\nall our losses and gains\nto see if our spendings defensible\n",
    "whats for breakfast some toast nah too small\nmaybe grapefruit too cold its the fall\nwell an egg yeah not bad\nlisten mom whats with dad\nits just dads breakfast waffle thats all\n",
    "we objected to what wed been shown\nand we forcefully made our views known\ntheir minor concession\nwont ease our aggression \ntheyve thrown us a meaningless bone\n",
    "take a numbers divisors  their sum\ncept the number itself though will come\nto a total repeat\non that answer this feat\ngot the first one theyre amicable dumb\n",
    "at first she was shy and withdrawn\nabandoned alone and forlorn\nthen encouraged and nourished\nshe blossomed and flourished \nunfurled like a flower at dawn\n",
    "the brushwood grows moist in the shade\nneath the trees at the edge of the glade\nwhere the sunlight can pour\nthick and sweet to the floor\nof the forest where tangles invade\n",
    "her brittleness shows in her gaze\nthose pinpricks are cold yet ablaze\nwith an icy denial\nof mercy that smile\nis cruel as her pitiless ways\n",
    "theres a door that you cannot ignore \nthough its locked whats beyond to explore\nif youre eager to see\nthen the bittings are key\ntheyre the bits that will open the door\n",
    "how dare you invade my sweet life\nyou bringer of conflict and strife\nuntil you came along\nnot a thing had gone wrong\nbut now discord and friction are rife\n",
    "in my time ive walked many a mile\nand ive climbed over many a stile\nthough i dont have a soul\nive two tongues i am whole\nas a pair hope my journeys worthwhile\n",
    "a blackouts a chilling sensation\nfirst dizziness then the formation\nof blackness that creeps\nacross vision and sweeps\nme away to a dark destination\n",
    "sweet mercy oh heaven forbid\nyou strangled that innocent kid\nhe shrugged his cold shoulders\nand blandly he told us\nwhy yes my dear people i did\n",
    "you can find one in h and in a\nin the middle there marking the way\nfrom the left to the right\nto prevent readers fright\nbarless hs cause lish dismay\n",
    "hes lying  we cannot deny it \nbut two can play games so lets try it\nsince none can believe him\nthis tale might deceive him\nin turn so you reckon hell buy it\n",
    "tig comes the shout and the chase\nstarts again so we dash for that place\nwhere we cannot get caught\nand where time can be bought\ncause in this game the bench is the base\n",
    "wouldst thou blench me thou dastardly rogue\nforsooth is the truth not in vogue\nwouldst thou cheat and deceive\nwouldst thou have me believe\ni should trust thee to handle my pogue\n",
    "your glibness is causing my blues\nyour witty remarks dont amuse\nyour tongue is too flip\nso button your lip\nyeah shut it  im sick of your views\n",
    "i dream of the havoc ill wreak\nin the pale shafts of moonlight so weak\nslanted rays form in bars\nand the smouldering stars\nglower down at me whisper  dont shriek\n",
    "im lonely im lost and i rage\nnevermore with this world to engage\nmy scars cannot heal\nbehind thick rods of steel\noh ill rattle the bars of this cage\n",
    " these points are remarkably clear\n theres no dense clump of writing to fear\n let me start a new line\n with a blob there its fine\n have you learnt about bullet points here\n",
    "great byzantium city of dreams\nevery street paved with gold how it gleams\nin a less jaded age\nthey wrote page after page\nof this balderdash screeds of it reams\n",
    "menelaus my husbanda joy\nbut young paris hes one sexy boy\ni dont hold with divorce\nor the scourge of remorse\nfor im bigamous helen of troy\n",
    "a bull terriers anything but\na great beauty this illfavoured mutt\nshows a shortness of leg\nhas a head like an egg\nand keeps his eyes practically shut\n",
    "the horizons renewed pinkish cast \ngentle tinge  shows that darkness is past\nif the dawns not forsaken\nthe sky will awaken\nwell see how long daylight will last\n",
    "reaching each chequered cranny and nook\nstolid castles play chess by the book\nleft to right front to back\non the white and the black \ntheyre reliable some prefer rook\n",
    "when the world seems depressingly grim\nand distressingly filled to the brim\nwith the bile of mankind\ncast those thoughts from your mind\nlest the light in your eyes grow too dim\n",
    "the dark in the garden alone\nthe moon casts its light on the stone\nbut the shadow thats cast\nby the stone will outlast\nany light that the night seems to own\n",
    "youre subtracting in columns dont try\ntaking nine from that two it wont fly\nthe solution is deft\nborrow ten from the left\nso that twelve minus nine will apply\n",
    "that algaefilled mirrorlike potion\nof sluggishness dregs of an ocean\nof ages it steers\nas it soaks up the years\nthe canal stagnant water in motion\n",
    "when youre choosing a name on the net\nwhat you call yourself helps you forget\nhow your flesh personalitys\ncolder mentalitys\nsomething youve learnt to regret\n",
    "break the surface reenter that world\nof the air where the mysteries that swirled\nunderwater are jailed\nby the twilight thats veiled\nand the loftier mysteries unfurled\n",
    "to capture the reticent grace\nof a smile on an innocent face\nyou must draw on an art\nuse your skill to impart\nlife and spark  every trace in its place\n",
    "though my mind in its bind may be marred\ni would journey though journeys are hard\nif i could through the peace\nand the blissful release\nof a world from which dreams were not barred\n",
    "when we talk about having the blues\ndepressions the very big news\nbut in life as in art\nblue gives joy to the heart\nwhen looked at in terms of its hues\n",
    "when he said im an artist he lied\nfor a gap on his canvas i spied\nand the edge was unkempt\nbut he sneered with contempt\ni am going to brush you aside\n",
    "id love to be sailing a dhow\nlying peacefully back on the bow\nto the sunset id float\nmy arabian boat \nbut im stuck in the grey hereandnow\n",
    "chief scientist davros who toiled\nwhile perpetual war raged and boiled\ncursed the doctor whose actions\ncreated infractions\nwith his daleks his plans were all foiled\n",
    "i dislike what they call cyber monday\nchristmas shopping should be a big fun day\nyou should visit each shop\ntil youre ready to drop\nan itookonthehighstreetandwon day\n",
    "colour rhymes arent sublime  its a crime\nthat you choose to use hues that dont chime\ndont say purple  ill moan\norange aint the right tone\nand with silver im ill verse should rhyme\n",
    "a day trip to london again\na day return ticket its plain\nyoure arriving past ten\na cheap day return then\nbecause this is the age of the train\n",
    "with a bottle brush bottles with dirtll\nbe cleaned out in no time  a fertile\nbeaufortia would do\ncallistemon makes two\nwellnamed substitutes kin to the myrtle\n",
    "i may vote upon blackburn in lancs\ntam dalyell told political ranks\nbut should they divest\nus of lothian west\nmay i vote on my blackburn  no thanks\n",
    "im poor and i live on my own\nand theyve cut off my lights and my phone\nwept old mother hubbard\nive emptied my cupboard\ni cant give my doggy a bone\n",
    "theres a catchy refrain in my brain\nworming round  it will drive me insane\nthough i liked it to start with\nim desperate to part with\nit now here it comes yet again\n",
    "their hostilitys calm they dont shriek\nbut neither one wants to seem weak\nand so neither will dare \nthough the others right there \nbreak that scathing sharp silence and speak\n",
    "there are things that you do every day\nin the selfsame unvarying way\nif you break them  thats swap them\nfor others or stop them \nthose habits no longer hold sway\n",
    "though goodbye could be cause to rejoice\nor a neutral and mutual choice\nthats delusion its fake\nyou can tell by the break \nthe emotional catch  in his voice\n",
    "september the foliage blushes \nis tinted with fiery flushes\nthe sunshine is patchy\nthe breezes are catchy\nthey swirl in their snatches and rushes\n",
    "weve broken the record surpassed\nevery previous team what a blast\nthough in truth its a shame\nto attain all this fame\nfor the number of times weve come last\n",
    "those snatches and fragments of song\ndrifting in from the street make me long\nfor those sweet afternoons\nwhen the catches of tunes\nthat i heard were more vivid and strong\n",
    "to beat means to strike or to pound\nor to flap so you rise from the ground\nas in beating your wings\nit can also mean things\nlike pulsate or defeat or confound\n",
    "for days upon spellbinding days\ni could fasten my glazedover gaze\non that shifting enthralling\nincessantly calling\nexpanse of the sea soul ablaze\n",
    "well tread this fresh ground more and more \nform a track where none travelled before\nsince your mousetraps the best\nall the worlds on a quest\nto beat out a path to your door\n",
    "ive been blooded i know that its wrong\nbut the taste and the smell are so strong\nim susceptible still\nto the chase and its thrill\nin pursuit of the kill i belong\n",
    "youre efficient and logical who\ncould deny we need more folks like you\nyour businesslike ways\nwill always bring praise\nthough its nice to be likeable too\n",
    "hes left his old mothers abode\nthis fairytale guys hit the road\nto seek fortunes to roam\nall he carries from home\nis his bundle a poor mans small load\n",
    "no no ive been tested and tried\nwont take money  just think of my pride\nme bribable never\nim bigger more clever\ntheres another door just round the side\n",
    "its a loudcelebrationsandmirthday\nand a whathavetheseyearsallbeenworthday\nthirteen springs since your birth \nwell whatever theyre worth\nzoe lou have a rockin good birthday\n",
    "got some data the orders a blight\nuse the bubble sort  quite a delight\nlet the algorithm churn\nchecking each pair in turn\nand youll find that theyre sorted just right\n",
    "this new broad gauge is thought to be great\nby brunel  but its got here too late\nfor the government hails\ngeorges narrowgauge rails\na slow death is brunels gauges fate\n",
    "dont shout as though part of a rabble\nspeak gently just murmur  dont gabble\nnow your undulant tone\nis still far from a drone\nits a burble you chatter and babble\n",
    "the sixyearold gazed bright eyes wide\nat the sparkling fairground and cried\nas the bumper cars rumbled\nenticingly jumbled\noh please can i have just one ride\n",
    "its only a tiny conjunction\nbut but has a critical function\nit indicates though\nthe preceding points so\ntheres a shift in my thoughts at this junction\n",
    "in peru i saw twelve campesinos \ntwelve farmers  on twelve palominos\nthey showed me the yield\nof their capsicum field\nand they each tossed me twelve jalapenos\n",
    "the canonical form we agree\nis the way an equation should be\nits a standard thats used\nso that no ones bemused\nsuch as y  mx  c\n",
    "though each panels a lively surprise\nthis cartoonist draws nothing but lies\nfor his characters smile\nbut are trapped in the bile\nhidden deep in their bubblegum eyes\n",
    "theres something afoot  be aware\nlets open our eyes and prepare\nthe tension keeps growing\nthe winds started blowing\nits brewing a storms in the air\n",
    "when life doesnt go as youve planned\nand the strife is too much to withstand\nyou pretend nothings wrong\nand youre jaunting along\nyou bury your head in the sand\n",
    "a sensation of deep fascination\ncan rapidly turn to fixation\nwhen enthralled by a theory\nwe rarely grow weary\nwere lost in intense captivation\n",
    "over rocks rainbow water will fall\nin cascades  hear the waterfalls brawl\nwith that ring as we listen\ntheyll sing and theyll glisten\ncascading cantabile all\n",
    "captivitys deadly repression\nprovokes a consuming obsession\nwith ways to escape\nand when tactics take shape\nand then fail i will turn to aggression\n",
    "when you alter its form or position\na nouns not beyond recognition\nits meanings the same\nbut inflections the game\nwith its case its syntactical mission\n",
    "but portia that doctor renowned\nruled that mercy unstrained could be found\nin the bond for no flood\nof that lifefluid blood\nwas along with the flesh fully bound\n",
    "come patter with raindrops asplatter\na drizzle or drenching or spatter \ncome sunshine or rain\nill be chanting again\nbut im casting a charm for the latter\n",
    "he told us a chilling old tale\nof a house where the floorboards would wail \nof the spirits whod shriek\nand the havoc theyd wreak \nand we laughed as we watched him turn pale\n",
    "though its stringy and merrily yellery\nsticklike and verily smellery\ntheres more on the scenery\nall of this greenery\naint necessarily celery\n",
    "with a circle i never get bored\nits perfect  so pleasing unflawed\non its curve i elect\nthese two points to connect\nnow the line that ive drawn is a chord\n",
    "from viewpoint to viewpoint youre ranging \nembracing then coldly estranging\nyou cant make your mind up\nand thats why you wind up\nincessantly chopping and changing\n",
    "im plummeting free and dont care\ngot a chute so ill tumble with flair\ntill its canopy spreads\nas it tugs on the threads\nand ill slow as it catches the air\n",
    "if youre working with wood my advice is\nthis short definition suffices\nto explicate bolt \nnot the lightning you dolt\nbut a log to be chopped into slices\n",
    "he whittled the willow beguiled\nby this woodfusion mild mixed with wild\nas the wind and her whistle\nset whispers abristle\nhe sighed and his carvingchild smiled\n",
    "its the term for the log getting hewed\nbut may also refer to whats viewed\nwhen the choppings all finished\nthe logs now diminished\nbut bolts short and round have accrued\n",
    "though it mightnt sound quite realistic\nmy philosophys basic simplistic\nmagic solvents and gold\nan elixir im sold\nmy ambitions and aims alchemistic\n",
    "that bite as my palms find the catch \nfor a moment im queen of this patch\nof the water that sings\nas my butterfly swings\nbody water a rapturous match\n",
    "ill unravel the riddles of old\nslay the dragon gain glory and gold\nby unfolding each scene\nin this story onscreen\nwith adventure games everyones bold\n",
    "its a property held by a gene\nbut just what does allelism mean\nbeing one of a set\nwhose distinct members let\nvariation between us be seen\n",
    "though darwinian selection is blind\nit is not by committee youll find\ncan camels lack grace\nthough designed with the place\nwhere they need to survive borne in mind\n",
    "we are atheist authors and know\ntheists think us irreverent whoa\nall the wonders unfurled\nin this mindblowing world\nmake our pantheist awe overflow\n",
    "in those timehonoured tales that theyve told us\nintending to scold us and mould us\nred riding hood goes\nfor a traipse in the snows\nwith her cardinal draped round her shoulders\n",
    "the mountains with cakeicing caps\nthe rivers that flow in their laps\nland ebbing and peaking\ncartographically speaking\nits there to be made into maps\n",
    "meet anu hes the star of the show\nlord of demons and dungeons below\nand the earth and the skies\nin sumerian eyes\nor he was six millenniums ago\n",
    "dear that scheme is distinctly depressing\nthe rates astronomic im guessing\nrenting land on uranus\nis likely to drain us \nno i dont think ill give it my blessing\n",
    "in court with his balance and knife\nhe was poised to take justice and life\nand to weigh out his fresh\npound of fair promised flesh\nthough the cries of sweet mercy were rife\n",
    "but  i will have my bond shylock cried\nfor his bloodlust would not be denied\ndebt unpaid he would menace\nthe merchant of venice\navenging his spatupon pride\n",
    "the caskets were gold silver lead\nbringing joy trepidation and dread\ntwo princes chose poorly\nbassanio demurely\nunlocked his loves portrait instead\n",
    "so bassanio not lender but spender\nwas furnished with ducats and splendour\nto belmont he sailed\nwith his purpose unveiled\nfor portia to be a contender\n",
    "antonio ventured beyond\nfriendships usual charge to respond\nto bassanios request\nfor at shylocks behest\nhe committed his flesh to a bond\n",
    "a torrent profusion parade\ninundation abundance arrayed\nfor an onslaught a surge\na bombardment a splurge\nthis collection of words a cascade\n",
    "when the metals so hot that it glows\nand then melts becomes fluid and flows\nthen its ready to cast\npour it quick thick and fast\ninto moulds to be shaped as you chose\n",
    "my buttoneared pup you need scolding\nthose ears flopping forwards and folding\nshould listen ill nuzzle\nyour blunt little muzzle\nand sniff you youre perfect for holding\n",
    "though the times were the worst and the best\nsydney cartons bleak life was not blessed\ntill he knelt in the shade\nof the guillotines blade\nand prepared for his far better rest\n",
    "so the moral that might be obtained\nfrom those bigots by love unrestrained\nthrough such prejudiced folks\nshakespeare shows us with jokes\nhow a tolerant world is less pained\n",
    "circulations gone down for our paper\nwere selling far fewer this taper\nis caused by the news\nwhich makes purchasers snooze\nseems theyd rather read vacuous vapour\n",
    "the eggandspoon racer limbs shaking\nwas inept at avoidance of breaking\nand with yolk all bemired\nas his muscles grew tired\nhe lamented my eggs started laking\n",
    "theres a stroke that i think is a cursed stroke\na battlebutrarelycomefirst stroke\na backwardsattack stroke\nto me its a slack stroke\ncause that stroke is backstroke my worst stroke\n",
    "through blackness and blueness he shifted\nshe too in her life only drifted\nbut the smile she produced\nwas a wonderful boost \nhe felt confident buoyant uplifted\n",
    "though a greatly distinguished professor\nrob wasnt that much of a guesser\nso he dithered and blanched\nwhen the woodland path branched \nthen he took the one travelled the lesser\n",
    "youre irate at the wait  ten to eight\nand the jam that you hate wont abate\nall the cars chockablock\ntraffic solid as rock\nand the tock of the clock says youre late\n",
    "her courtesy only confirms\nshe considers us pitiful worms\nsince shes civil  polite \nwhilst repressing her bite\ngood manners when chilly cause squirms\n",
    "thats benedick poor maligned man\nfighting beatrice as well as he can\nwith his clowning and sparring\ntheyre ceaselessly jarring\nand both have for marriage no plan\n",
    "and the watch comes with news for the cause\nheres borachio caught he gives pause\nto harsh claudios fury\nconfessing oh jury\nshes blameless  theyre mine heros flaws\n",
    "no not dead  but the wedding though started\nhas fallen apart hes departed\nand shes been belied\nwhat to do say shes died\nand good claudio wont stay hardhearted\n",
    "in his foxscented coat natures plush\nhe pauses one paw raised then  hush \nas his nose gently pushes\nthrough midnightlit bushes\nhe holds high his tail or his brush\n",
    "youll be callow my chickling my own\ntill youve sprouted your feathers and flown\ncome away from the edge\nor youll fall from this ledge\nyou can fly when youre fledged  when theyve grown\n",
    "back and forth he has carried the news \nnow from south back to north hes brought views\nto the leaders who heard\nnot his voice but his word\nnow their own marches miles in his shoes\n",
    "haphazardly cutting and shearing\nthe corners youre swerving and veering\nthis neckbreaking speeding\nis leaving you leading\ncareening and keenly careering\n",
    "hear the towns rotting welcome sign creak\nnow its long past its affluent peak\nonce it bustled and thrived\nbut it cant be revived\nits a carcass left empty and bleak\n",
    "your start in the world is a mess\nbut you dont have to wallow in stress\nthough youre left on your own\nby your efforts alone\nyou can bootstrap yourself to success\n",
    "though a pale winters dawn may be splendid\nits freezing  has night really ended\nim glad im awake\nas the day starts to break\nbut i sure hope the sunshine gets mended\n",
    "shes a rock standing firm through the strife\na good daughter and sister and wife\nraising children who care\nthere her capstones laid theyre\npetras crowning achievement in life\n",
    "if it seems that you merely survive \njust exist  dont feel thankful or thrive\nsimply pause for one breath \nnot to think about death\nbut to savour that instant alive\n",
    "with a blade mark your name into ice\nit will melt into water each slice\ncarve your name into stone\nit will stay there alone\nfor a long geological trice\n",
    "box the compass thats easy  im grinning\nsimply start with the north the beginning\nnorth by east follows that\nnorthnortheasts where its at\nfor the next bit my heads started spinning\n",
    "hes always more grinning than grim\nhell playfully act on a whim\nhis reasonings specious\nhes often facetious\nhes blithe and capricious  thats him\n",
    "some poetry once in a while\nemploys archilochian style\niambic satirics \ninvention in lyrics \nits written with gusto and guile\n",
    "a blanket terms frequently heard\nto generalise greatly absurd\nthe confusions made worse\nsince the groups so diverse\nthe distinctions get buried or blurred\n",
    "hear that sound  it is music to me \nof water on rocks in the sea\nthat soullifting brawl\nmakes my heart stand up tall\nits so fresh and so wild i feel free\n",
    "for optimal teaching and learning\nthey stuck us in sets how discerning\nthe groups are the best\nthe slowest the rest\nits called banding and bitter were turning\n",
    "when youre woebegone down feeling low\nyou need someone to whom you can go \nwho will help you take stock\nas your mainstay your rock\nand your anchor you need one you know\n",
    "i try not to swear or to curse\nsince its dumb and makes everything worse\ninstead i say blast\nits a word unsurpassed\nin its mildness for usage in verse\n",
    "im someone whos rarely arrayed\nin glamorous glitz im not swayed\nby the teens and their scenes\ncause i like these old jeans\ni dont care that theyre faded and frayed\n",
    "the metals sharp shine will entice\nme to skate on the rink in a trice\neach boot with its blade\nlends me speed thats displayed\nas i slice across shimmering ice\n",
    "compound levers are truly highflyers \nalmost all a designer desires\nat the fulcrum two levers\nare hinged such achievers\nare nutcrackers scissors and pliers\n",
    "shes cheerless and chilly behold\nhow shell scathingly snappily scold\nshes distant disdainful \nfinds friendliness painful\nshes frigid and frosty shes cold\n",
    "nope youre cold freezing cold cold as ice\nshe says gleefully sisters so nice\noh thats warmer a bit\nnope youre cold let me quit\nive explored the whole house almost  twice\n",
    "set aside all that billowing ocean\nof sentiment mindful devotion\nto rational thought\nhelps you judge as you ought\ncold logic beats skittish emotion\n",
    "hosting lunch for a dieting group\nshe had proffered a drink with their soup\nand the cork wrested out\nfrom the wine bottles spout\nmade a sound that is known as a cloop\n",
    "this design shows two circles one snared\nin the bounds of the other theyre paired\nwith enchanting simplicity\nand suave concentricity\ntwo circles one centre thats shared\n",
    "with the help of some fitting statistics\nwe chart in contrastive linguistics\nhow lingos compare\ndo they differ and where\nin their lexicons grammars stylistics\n",
    "the clackety metrical feet\nof the train as i curl on my seat\nin a travelworn heap\nalmost lull me to sleep\nwith a cadenced and rhythmical beat\n",
    "youre terse sometimes brusque sometimes blunt\nyou dont waffle you rarely confront\nany issue digressing\nfrom what youre addressing\nbut conciseness does not mean a grunt\n",
    "education should aim to enhance\nchildrens thinking when given the chance\ngrowing minds can be freed\nfrom a church schools old creed\nteach them wonder and truth  thats our stance\n",
    "dont hop down the lane quite at ease\nstay away from our orbeyeballs please\nor these dreadlamps will find you\nto bind you and blind you \nensnared and bedazzled youll freeze\n",
    "to hermes in winged sandals shod\nthe caduceus whiteribboned rod\ngave the power to harm\nor to heal and to calm\nas a tool for this messenger god\n",
    "this cool moving air is a treat\nafter stagnant and harrowing heat\nthe breath that will kiss you\nthat feeling of bliss you\nhave missed for so long  fresh and sweet\n",
    "with iron they taught me that sin\nburrows deeper than scars on my skin\nthat singemark will last\nand will dredge up the past\nim branded without and within\n",
    "between thick knotted branches i lie\nstaring up from this tree i could fly\ntwisted limbs are ensnarled\nwith each other and gnarled\nin a lattice that splinters the sky\n",
    "suffragettes when in prison campaign\nbut their hunger strikes sadly in vain\nsince the powers meow\ncat and mouse act allow\ntheir release  till theyre healthy again\n",
    "the sand stretches on by the mile\nindistinguished  each shifting soft pile \nby the bake of the sun\nbeating down days begun\nwith the heat and restraint i revile\n",
    "in the depths of your mind in the night\nyou are frozen then frenzied take flight\nat the bark of the guns\nas their stark harshness stuns\nand you struggle awake  towards light\n",
    "this websites deliciously strewn\nwith our verses  not quite all in tune\nso well beaver away\nthrough the night and the day\nand theyll all read like dreams pretty soon\n",
    "this canopy blinds me with blue\nthough the dawn and its dew are still new\nautumn sun low and bright\nwith its cold burnished light\nleaves the sky as a stark empty view\n",
    "at the altar next morning  his pride\nbadly wounded  he turns on his bride\nshe is rotten impure\nthis i cannot endure\nand she falls  poor wronged hero has died\n",
    "with the girls future husband in tow\ndon john hides in the shadows below\nwhile borachio sighs\noh sweet hero he lies\nbut poor claudio isnt to know\n",
    "and don john is still seething with spite \ntheres a breakup he wants to incite\nso he brews up a plan\nlet the friends see a man\nnext to heros dark window by night\n",
    "with the two feisty bs still at war\nand the wait for the wedding a bore\nall their friends restless scheme\ntheyre a matchmaking team\nspreading heartthrobbing rumours galore\n",
    "although claudio anguished bewails\nthe sad loss of his darling tall tales\nlike don johns cant last long\nso they right that cruel wrong\nnow for marriage theres wind in the sails\n",
    "but don johns a malevolent foe\nhes a backstabbing traitor and so\nhe says claudios tricked\nand don pedro has picked\nthat young maid for himself oh the woe\n",
   
 ]